
= Planix

== Client

Normally starts from the shell and goes into the background.
Can write to stdout.
Connects to the server/broker through MQTT

== Registration

Client looks for `.planix` and gets the _team hash_ from it.

The team hash is used to register with the broker.

User name is taken from git config or current username

Messages are mostly designed to be one-way, informative.
Persistent data should be stored in git repo


== Messages

<thash>/<user>/<action>/<args>

== Actions

    checkin - Flag me as available, not idle.
    touch/<file> - I am working on file

    msg/<user> - Private message

doc/<name> - Here is doc

== Service less functionality

Say things to users
Online status of users

thash/sasq/action : "Checked in test.c" (not retained)

Logging services saves it


thash/sasq/status "online" (retained)
last will: "offline"

subscribe thash/#/status will show all users status




== Services

`chat`

Listens for <thash>/#/say
Saves 


== Message Board

Special MQTT client

Posting:

Send post/<topic>

Board will add to text file and commit to board repo
Board will send post to subscribers



CODE

If server not running, start in background

Server:

Run MQTT thread.
Put incoming messages in thread safe queue
Read outgoing messages from other queue

Client:

Talk to sever via pipe

Server does not send anything back, reports via stdout

